---
# ------------------------------------------------
# Authorino Operator
# ------------------------------------------------
ocp4_workload_authorino_operator_namespace: openshift-operators

ocp4_workload_authorino_operator_channel: stable
ocp4_workload_authorino_operator_automatic_install_plan_approval: true
ocp4_workload_authorino_operator_starting_csv: ""
ocp4_workload_authorino_operator_wait_for_deploy: true

ocp4_workload_authorino_operator_use_catalog_snapshot: false
ocp4_workload_authorino_operator_catalogsource_name: ""
ocp4_workload_authorino_operator_catalog_snapshot_image: quay.io/rhpds/olm_snapshot_redhat_catalog
ocp4_workload_authorino_operator_catalog_snapshot_image_tag: v4.19_2025_07_21

ocp4_workload_authorino_operator_deploy_authorino: false
ocp4_workload_authorino_operator_authorino_name: authorino
