---
galaxy_info:
  role_name: ocp4_workload_connectivity_link
  author:
  - Wolfgang Kulhanek <wkulhane@redhat.com>
  description: |
    Deploys Connectivity Link Operator to an OCP4 cluster
  platforms: []
  license: GNU General Public License v3.0
  galaxy_tags:
  - ocp4
  - openshift
  - kubevirt
  - kuadrant
  - connectivity-link
  - cnv
dependencies: []
