---
# --------------------------------
# Common settings for all auth providers
# --------------------------------
ocp4_workload_authentication_admin_create: true
ocp4_workload_authentication_admin_username: admin

# Admin password. If set to empty string then a password will be generated.
ocp4_workload_authentication_admin_password: ""

# Length of password if generated for admin user.
ocp4_workload_authentication_admin_password_length: 10

# Optional cluster accounts if accounts other than admin should be created.
# These cluster accounts are created in the authentication provider but are
# not reported as users with `agnosticd_user_info` and so do not create
# seats for workshop usage.
#
# An admin account with cluster-admin access is automatically added to the list
# of cluster accounts if ocp4_workload_authentication_admin_create is true.
# Ex:
#ocp4_workload_authentication_cluster_accounts:
#- name: cluster-reader
#  cluster_role: cluster-reader
#  password: reader
#- name: developer
#  password_length: 8
ocp4_workload_authentication_cluster_accounts: []

# Optional common password for all cluster user accounts.
ocp4_workload_authentication_cluster_account_password: ""

# Generate a separate password for each cluster user account.
ocp4_workload_authentication_cluster_account_password_randomized: true

# Configure whether and how many numbered users to create.
ocp4_workload_authentication_num_users: "{{ num_users | default(0) }}"

# Configure user naming for multiuser mode.
# This toggle determines whether a single user configured with a numeric
# suffix, ex `user1` using `ocp4_workload_authentication_user_basename` or
# whether it uses `ocp4_workload_authentication_user_name for` the user name.
# It also controls account naming when multiple accounts are created per-user.
#
# If the service has a parameter for the number of users that can be 1 or
# higher then then this should be explicitly set to true for consistent user
# naming when ordered with just one user.
ocp4_workload_authentication_multiuser: >-
  {{ ocp4_workload_authentication_num_users | int > 1 }}

# Base name prefix for numbered users
ocp4_workload_authentication_user_basename: user

# User name to use when only a single "numbered" user is requested.
# This user is reported like numbered users with `agnosticd_user_info`
# to allow separating environment data from data exposed to end users,
# for example as workshop seats.
ocp4_workload_authentication_user_name: user

# Common user password for numbered users. If left empty then a password will
# be generated.
ocp4_workload_authentication_user_password: ""

# Length of password generated for user.
ocp4_workload_authentication_user_password_length: 10

# Generate a separate password for each numbered user account.
ocp4_workload_authentication_user_password_randomized: true

# Account names to create for each user.
# Default is to create a single account for each user named with either
# ocp4_workload_authentication_user_name for single user deployment or
# ocp4_workload_authentication_user_basename followed by the numerical
# suffix for multiple users.
ocp4_workload_authentication_per_user_account_names:
- >-
  {{
    ocp4_workload_authentication_user_basename
    if ocp4_workload_authentication_multiuser | bool else
    ocp4_workload_authentication_user_name
  }}

# Remove secret for kubeadmin user access created in initial cluster installation.
ocp4_workload_authentication_remove_kubeadmin: true

# Select auth provider: htpasswd or keycloak
ocp4_workload_authentication_provider: htpasswd

# --------------------------------
# Htpasswd Settings
# --------------------------------
ocp4_workload_authentication_htpasswd_secret_name: htpasswd

# --------------------------------
# Keycloak Settings
# --------------------------------

ocp4_workload_authentication_keycloak_namespace: keycloak

ocp4_workload_authentication_keycloak_pgsql_user: keycloak

ocp4_workload_authentication_keycloak_pgsql_password: ""

ocp4_workload_authentication_keycloak_channel: stable-v26.2

ocp4_workload_authentication_keycloak_automatic_install_plan_approval: true

ocp4_workload_authentication_keycloak_starting_csv: ""

ocp4_workload_authentication_keycloak_use_catalog_source: false

ocp4_workload_authentication_keycloak_catalogsource_image: quay.io/rhpds/olm_snapshot_redhat_catalog

ocp4_workload_authentication_keycloak_catalogsource_tag: v4.20_2026_02_11

ocp4_workload_authentication_keycloak_default_realm: sso

ocp4_workload_authentication_keycloak_default_groups:
- name: admins
- name: users

ocp4_workload_authentication_keycloak_openshift_client_secret: ""

ocp4_workload_authentication_keycloak_openshift_client_id: idp-4-ocp

ocp4_workload_authentication_keycloak_enable_user_info_messages: true
