---
# From secrets based on cluster to deploy to
ocp4_workload_external_odf_guest_config: ""
ocp4_workload_external_odf_guest_pool: ""

ocp4_workload_external_odf_registry_size: 100Gi
ocp4_workload_external_odf_ceph_storage_system_deploy_timeout: 500

ocp4_workload_external_odf_backingstore_pv_volumes: 3
ocp4_workload_external_odf_backingstore_custom_resources: false
ocp4_workload_external_odf_backingstore_cpu_limits: 1000m
ocp4_workload_external_odf_backingstore_cpu_requests: 800m
ocp4_workload_external_odf_backingstore_memory_limits: 4000Mi
ocp4_workload_external_odf_backingstore_memory_requests: 800Mi
ocp4_workload_external_odf_backingstore_storage_requests: 50Gi

ocp4_workload_external_odf_noobaa_deploy_timeout: 600

ocp4_workload_external_odf_noobaa_custom_resources: false
ocp4_workload_external_odf_noobaa_memory_limits: 4Gi
ocp4_workload_external_odf_noobaa_memory_requests: 4Gi
ocp4_workload_external_odf_noobaa_cpu_limits: 3
ocp4_workload_external_odf_noobaa_cpu_requests: 3

ocp4_workload_external_odf_volume_binding_mode: WaitForFirstConsumer

ocp4_workload_external_odf_registry_storage_class: ocs-external-storagecluster-ceph-rbd

ocp4_workload_external_odf_operator_namespace: openshift-storage
ocp4_workload_external_odf_channel: stable-4.18
ocp4_workload_external_odf_operator_automatic_install_plan_approval: true
ocp4_workload_external_odf_operator_starting_csv: ""
ocp4_workload_external_odf_operator_use_catalog_snapshot: false
ocp4_workload_external_odf_operator_catalog_source_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_external_odf_operator_catalog_source_tag: "v4.18_2025_10_23"