---
- name: Remove kubeadmin user
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    name: kubeadmin
    namespace: kube-system
  register: r_remove_kubeadmin
  retries: 5
  delay: 10
  until: r_remove_kubeadmin is success
